### ISSUE TITLE
Errors: cannot use all pre-periods in F test / covariance matrix is irreversible

### ISSUE THREAD

**Issue by nthrpy** [xuyiqing/fect#39]
Dear Prof. Xu-

I encountered the following errors often when using ife:

Cannot use full pre-treatment periods in the F test. The first period is removed.
The estimated covariance matrix is irreversible.

Here is the simulated time-series and also the fect parameters:
![image](https://github.com/xuyiqing/fect/assets/170206388/45106d81-eee6-4b32-9eaa-e850b71c0458)
![image](https://github.com/xuyiqing/fect/assets/170206388/bf85ea40-3345-42a0-9d7a-5f7da8ae11c5)

Why do these errors occur?
How do I avoid them?

Thank you!

**Comment by lzy318** [comment]
This is because the number of treated units is smaller than the number of pre-treatment periods, so it can't implement the F-test for all pre-treatment periods. However, you can specify a shorter pre-treatment periods for testing, e.g., add the option pre.periods = c(-3,0) to test for the pretrend in the last 4 pre-treatment periods.

**Comment by nthrpy** [comment]
Your recommendation solves the problem. Thank you!
